// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBytvERGo0qy5xTj1aZl6mjdm0cJsclyLc',
    appId: '1:315811585941:web:e92524e4b4c9f036a5a09c',
    messagingSenderId: '315811585941',
    projectId: 'proyecto-appnotasflutter',
    authDomain: 'proyecto-appnotasflutter.firebaseapp.com',
    storageBucket: 'proyecto-appnotasflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwBso-xuutkJ8WC2f7xFdX9gscyDZFSbE',
    appId: '1:315811585941:android:bf7dc03625e28d44a5a09c',
    messagingSenderId: '315811585941',
    projectId: 'proyecto-appnotasflutter',
    storageBucket: 'proyecto-appnotasflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSYNfFWgnkyr_tdt9B9sVhKP7oryr8Bw',
    appId: '1:315811585941:ios:a9b362c2911aba95a5a09c',
    messagingSenderId: '315811585941',
    projectId: 'proyecto-appnotasflutter',
    storageBucket: 'proyecto-appnotasflutter.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAppnotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUSYNfFWgnkyr_tdt9B9sVhKP7oryr8Bw',
    appId: '1:315811585941:ios:a9b362c2911aba95a5a09c',
    messagingSenderId: '315811585941',
    projectId: 'proyecto-appnotasflutter',
    storageBucket: 'proyecto-appnotasflutter.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAppnotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBytvERGo0qy5xTj1aZl6mjdm0cJsclyLc',
    appId: '1:315811585941:web:e6cc349ee8bd157da5a09c',
    messagingSenderId: '315811585941',
    projectId: 'proyecto-appnotasflutter',
    authDomain: 'proyecto-appnotasflutter.firebaseapp.com',
    storageBucket: 'proyecto-appnotasflutter.appspot.com',
  );
}
