name: Flutter Contruccion

on: 
  push:
    branches: [" master "]
jobs:  

  build: 
    runs-on: ubuntu-latest  

    steps:  

    - uses: actions/checkout@v4  
    - name: Usar Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - uses: actions/setup-java@v4
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 

    - run: flutter pub get
